name: create_introductions_issues

channels:
  - conda-forge

dependencies:
  - appnope
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pip
  - pytest
  - tqdm
  - pip:
    - build
    - bump2version
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-jupyter
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - placekey
    - twine
